name: graphql_client_generator
description: A starting point for Dart libraries or applications.
version: "0.0.1"
author: Dustin Graham <dgraham@rtafleet.com>
# homepage: https://www.example.com

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.13.3
  built_value: ^8.0.5
  built_collection: ^5.0.0
  graphql_dart: any
  source_gen: ^1.0.0
  recase: ^3.0.0
  graphql_parser: ^1.1.3
  build_runner: ^2.0.2
  built_value_generator: ^8.0.5
  code_builder: ^4.0.0

dev_dependencies:
  test: ^1.6.1
  mockito: ^4.0.0

executables:
  graphql-client-generator: graphql_client_generator

dependency_overrides:
  build_config: ^1.0.0
  build_runner: ^2.0.2
  graphql_dart:
    path: ../graphql_dart