name: graphql_client_generator
description: A starting point for Dart libraries or applications.
version: "0.0.1"
author: Dustin Graham <dgraham@rtafleet.com>
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  built_value: ^8.9.0
  built_collection: ^5.1.1
  graphql_dart: any
  source_gen: ^1.5.0
  recase: ^4.1.0
  graphql_parser2: ^6.2.0
  build_runner: ^2.4.8
  built_value_generator: ^8.9.0
  code_builder: ^4.10.0

dev_dependencies:
  test: ^1.24.0
  mockito: ^5.4.4

executables:
  graphql-client-generator: graphql_client_generator

dependency_overrides:
  http_parser: ^4.0.0
  graphql_dart:
    path: ../graphql_dart