name: graphql_dart
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com
# author: dustin <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.13.3
  graphql_parser: ^1.0.0

dev_dependencies:
  test: ^1.0.0
  mockito: ^4.0.0
